// <auto-generated />
namespace MotoDataBase.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class initialzed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initialzed));
        
        string IMigrationMetadata.Id
        {
            get { return "201911181651487_initialzed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
